README.md
onResume was not calling super.onResume() on the documentation for the components module.
=> Small error on README.md file: onResume was not calling super.onResume()

rxlifecycle/src/main/java/com/trello/rxlifecycle/RxLifecycle.java, rxlifecycle/src/test/java/com/trello/rxlifecycle/RxLifecycleTest.java
Before, it would throw an exception, which doesn't make as much sense - if
the logic worked out such that you bound outside the lifecycle, that prboably
meant that you just don't want the subscription to occur outside the
lifecycle, so it should end immediately.
Fixes #23
=> Binding outside lifecycle causes instant completion

rxlifecycle/src/main/java/com/trello/rxlifecycle/RxLifecycle.java, rxlifecycle/src/test/java/com/trello/rxlifecycle/RxLifecycleTest.java
Also added a bunch of tests that the null checks are working
=> Moved null-checking up to front of methods

rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/ActivityLifecycleProvider.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/FragmentLifecycleProvider.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/RxActivity.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/RxDialogFragment.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/RxFragment.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/support/RxAppCompatActivity.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/support/RxDialogFragment.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/support/RxFragment.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/support/RxFragmentActivity.java, rxlifecycle/src/main/java/com/trello/rxlifecycle/RxLifecycle.java
Return type `Transformer<T, T>` was updated to `Transformer<? super T, ? extends T>` to support Kotlin type inference.
This should fix #44 issue.
=> Updated Transformer's generic parameters

rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/RxActivity.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/RxDialogFragment.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/RxFragment.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/support/RxAppCompatActivity.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/support/RxDialogFragment.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/support/RxFragmentActivity.java
The advantage is pretty simple. When you extend from one of these classes and override one method but don't call the super method you'll get a warning in Android Studio.
=> Add CallSuper annotation to provided Activity, Context and Dialog components

rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/RxActivity.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/RxDialogFragment.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/RxFragment.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/support/RxAppCompatActivity.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/support/RxDialogFragment.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/support/RxFragment.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/support/RxFragmentActivity.java, rxlifecycle-components/src/test/java/com/trello/rxlifecycle/components/RxActivityLifecycleTest.java, rxlifecycle-components/src/test/java/com/trello/rxlifecycle/components/RxFragmentLifecycleTest.java, rxlifecycle-components/src/test/java/com/trello/rxlifecycle/components/support/RxSupportFragmentLifecycleTest.java, rxlifecycle/src/main/java/com/trello/rxlifecycle/ActivityLifecycleProvider.java, rxlifecycle/src/main/java/com/trello/rxlifecycle/FragmentLifecycleProvider.java
This will allow multiple implementations of the provider to
exist without having everyone depending on rxlifecycle-components
=> Moved Provider interfaces into core library

README.md, build.gradle, rxlifecycle-kotlin/build.gradle, rxlifecycle-kotlin/gradle.properties, rxlifecycle-kotlin/src/main/AndroidManifest.xml, rxlifecycle-kotlin/src/main/java/com/trello/rxlifecycle/kotlin/rxlifecycle.kt, settings.gradle
address reverted #58 , and some nice new syntax
Not sure if any tests will work here.
=> rxlifecycle-kotlin module added with bind() syntax

README.md, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/RxActivity.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/RxDialogFragment.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/RxFragment.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/support/RxAppCompatActivity.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/support/RxDialogFragment.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/support/RxFragment.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/support/RxFragmentActivity.java, rxlifecycle-navi/src/main/java/com/trello/rxlifecycle/navi/ActivityLifecycleProviderImpl.java, rxlifecycle-navi/src/main/java/com/trello/rxlifecycle/navi/FragmentLifecycleProviderImpl.java, rxlifecycle/src/main/java/com/trello/rxlifecycle/RxLifecycle.java, rxlifecycle/src/test/java/com/trello/rxlifecycle/RxLifecycleTest.java
In hindsight, it was totally unnecessary to split them up, since the
type checker will prevent you from binding FragmentEvents to
ActivityEvent streams and vice versa.
Partially addresses #76
=> Made bindUntilEvent() public, deprecated more specific calls

rxlifecycle/src/main/java/com/trello/rxlifecycle/RxLifecycle.java, rxlifecycle/src/test/java/com/trello/rxlifecycle/RxLifecycleTest.java
Also deprecated one bindView() method because its name was
completely misleading (it had nothing inherently to do with Views).
Fixes #76
=> Opened up bind() methods

rxlifecycle-navi/src/main/AndroidManifest.xml
This is done by mistake, right?
I understand that there is no point to use both navi and component bindings in same project, but i need to migrate, and it wouldn't be in a single commit.
So if one add both dependencies:
```
compile 'com.trello:rxlifecycle-components:0.5.0'
compile 'com.trello:rxlifecycle-navi:0.5.0'
```
it leads to
```
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lcom/trello/rxlifecycle/components/BuildConfig;
```
=> fix navi package

rxlifecycle/src/main/java/com/trello/rxlifecycle/LifecycleTransformer.java, rxlifecycle/src/main/java/com/trello/rxlifecycle/RxLifecycle.java, rxlifecycle/src/main/java/com/trello/rxlifecycle/TakeUntilGenerator.java, rxlifecycle/src/main/java/com/trello/rxlifecycle/UntilCorrespondingEventObservableTransformer.java, rxlifecycle/src/main/java/com/trello/rxlifecycle/UntilCorrespondingEventSingleTransformer.java, rxlifecycle/src/main/java/com/trello/rxlifecycle/UntilEventObservableTransformer.java, rxlifecycle/src/main/java/com/trello/rxlifecycle/UntilEventSingleTransformer.java, rxlifecycle/src/main/java/com/trello/rxlifecycle/UntilLifecycleObservableTransformer.java, rxlifecycle/src/main/java/com/trello/rxlifecycle/UntilLifecycleSingleTransformer.java, rxlifecycle/src/test/java/com/trello/rxlifecycle/LifecycleTransformerTest.java, rxlifecycle/src/test/java/com/trello/rxlifecycle/UntilCorrespondingEventObservableTransformerTest.java, rxlifecycle/src/test/java/com/trello/rxlifecycle/UntilCorrespondingEventSingleTransformerTest.java, rxlifecycle/src/test/java/com/trello/rxlifecycle/UntilEventObservableTransformerTest.java, rxlifecycle/src/test/java/com/trello/rxlifecycle/UntilEventSingleTransformerTest.java, rxlifecycle/src/test/java/com/trello/rxlifecycle/UntilLifecycleObservableTransformerTest.java, rxlifecycle/src/test/java/com/trello/rxlifecycle/UntilLifecycleSingleTransformerTest.java
Via `LifecycleTransformer`, which allows us to keep the baseline support for `Observable.Transformer` but also a simple way to turn it into a `Single.Transformer`.
Fixes #39
=> Added support for Single

rxlifecycle-kotlin/src/main/java/com/trello/rxlifecycle/kotlin/rxlifecycle.kt
The Kotlin extensions are super useful, but they were missing for Singles and Completables. This PR adds them in.
I also shortened each line for readability purposes.
=> Add Kotlin extensions for Singles and Completables

rxlifecycle/src/main/java/com/trello/rxlifecycle/ActivityLifecycleProvider.java, rxlifecycle/src/main/java/com/trello/rxlifecycle/FragmentLifecycleProvider.java, rxlifecycle/src/main/java/com/trello/rxlifecycle/LifecycleProvider.java
This adds a superinterface that contains the three methods shared by the `ActivityLifecycleProvider` and `FragmentLifecycleProvider` classes.
=> Add LifecycleProvider superinterface for ActivityLifecycleProvider and FragmentLifecycleProvider

build.gradle
Otherwise this will happen in AS:
> Error:Android plugin 2.1.0 is not compatible with Gradle 2.14.1.
=> Update to latest Gradle Android Tools (2.1.3)

build.gradle, rxlifecycle/src/test/java/com/trello/rxlifecycle/UntilCorrespondingEventSingleTransformerTest.java, rxlifecycle/src/test/java/com/trello/rxlifecycle/UntilEventSingleTransformerTest.java, rxlifecycle/src/test/java/com/trello/rxlifecycle/UntilLifecycleSingleTransformerTest.java
The tests errantly believed that Single was backpressure aware. It's
not. Now we use a TestScheduler to control the emissions of the
Single for timing purposes.
=> Upgraded to support RxJava 1.2.1

rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/RxActivity.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/RxDialogFragment.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/RxFragment.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/RxPreferenceFragment.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/support/RxAppCompatActivity.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/support/RxAppCompatDialogFragment.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/support/RxDialogFragment.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/support/RxFragment.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle/components/support/RxFragmentActivity.java, rxlifecycle-components/src/test/java/com/trello/rxlifecycle/components/RxActivityLifecycleTest.java, rxlifecycle-components/src/test/java/com/trello/rxlifecycle/components/RxFragmentLifecycleTest.java, rxlifecycle-components/src/test/java/com/trello/rxlifecycle/components/support/RxSupportFragmentLifecycleTest.java
This both prevents the compiler from warning about unregistered
Activities and also signals to users that these classes are intended
to be subclassed.
=> Made all components abstract

rxlifecycle/src/main/java/com/trello/rxlifecycle/Functions.java, rxlifecycle/src/main/java/com/trello/rxlifecycle/UntilCorrespondingEventTransformer.java, rxlifecycle/src/main/java/com/trello/rxlifecycle/UntilEventTransformer.java, rxlifecycle/src/main/java/com/trello/rxlifecycle/UntilLifecycleTransformer.java
Just saw it while you were changing the Completable.ambArray call
Not only less methods that are being used. `flatMapCompletable` is also faster since the entire 'flattening' part is left out and internal optimizations can be applied since it knows that Completable either completes or errors.
=> Leverage flatMapCompletable

rxlifecycle/build.gradle
This is the same fix as #219, but on the `1.x` branch for projects that haven't been able to migrate to RxJava2 yet.
I checked and it doesn't look like `javax.annotation.Nonnull` is used anywhere in the Android modules, so I didn't need to change any annotation usages.
=> Make JSR 305 compileOnly on 1.x branch

rxlifecycle-android-lifecycle-kotlin/src/main/java/com/trello/rxlifecycle2/android/lifecycle/kotlin/rxlifecycle.kt
Remove the unecessary generic type <T> from the kotlin extensions for binding to Completable chains. The type declared in the signature is not being used in the function, and doesn't make sense on a Completable, so this looks like a copy/paste error.
This fixes the following error, when not specifying a type:
Type inference failed: Not enough information to infer parameter T in fun <T> Completable.bindUntilEvent(owner: LifecycleOwner, event: Lifecycle.Event): Completable
=> Remove generic type declaration for Completable bindings.

.travis.yml, build.gradle, rxlifecycle-android-lifecycle/src/test/java/com/trello/rxlifecycle2/android/lifecycle/AndroidLifecycleActivityTest.java, rxlifecycle-android-lifecycle/src/test/java/com/trello/rxlifecycle2/android/lifecycle/AndroidLifecycleFragmentTest.java
This change makes `com.trello.lifecycle2.android.lifecycle.AndroidLifecycle_LifecycleProvider ` implements `android.arch.lifecycle.GeneratedAdapter`.
Fixes #245
=> Update android arch lifecycle version

README.md, rxlifecycle-navi/src/main/java/com/trello/rxlifecycle2/navi/NaviLifecycle.java
Navi itself is being deprecated and rxlifecycle-android-lifecycle
works just as well (if not better).
=> Deprecating rxlifecycle-navi

build.gradle, rxlifecycle-components/src/main/java/com/trello/rxlifecycle3/components/support/RxAppCompatActivity.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle3/components/support/RxFragment.java, rxlifecycle-components/src/main/java/com/trello/rxlifecycle3/components/support/RxFragmentActivity.java
Latest AndroidX AppCompat library supports LayoutId constructor.
https://developer.android.com/jetpack/androidx/releases/appcompat#1.1.0
I want to RxLifecycle's RxAppCompatActivity ,etc... supports that constructor.
=> Support LayoutId constructors for AppCompatActivity and (AndroidX)Fragment

rxlifecycle-android-lifecycle-kotlin/src/main/AndroidManifest.xml
Not sure how this ended up being so randomly weird, but it was not following
conventions. In particular, it should be namespaced to the version of rxlifecycle
so that we're not having any collisions between different major versions.
Fixes #329
=> Corrected package name in rxlifecycle-android-lifecycle-kotlin

rxlifecycle-android-lifecycle-kotlin/build.gradle, rxlifecycle-kotlin/build.gradle, settings.gradle
Otherwise you can't use different major versions of RxLifecycle side-by-side
due to the generated .kotlin_module file.
Fixes #329
=> Namespace Kotlin module names
